// VideoPlugin.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(VideoPlugin.tlb)，该类型库将成为
// VideoPlugin.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(55EABC41-EF6C-498C-B968-66993811FF2B), version(1.0),
  control ]
library VideoPluginLib
{
	importlib(STDOLE_TLB);

	//  CVideoPluginCtrl 的主调度接口
	[ 
		uuid(C29B30E6-DE9E-4C9D-A5BD-3328A6F3FC57)	
	]
	dispinterface _DVideoPlugin
	{
		properties:
		methods:
			[id(1)] void OnWindowClose(void);
			[id(2)] void OnVideoStart(void);
	};

	//  CVideoPluginCtrl 的事件调度接口

	[ 
		uuid(512A767A-EBA8-49D6-AA9D-1BFE34A0D7B4)	
	]
	dispinterface _DVideoPluginEvents
	{
		properties:
			//  事件接口没有任何属性
			[id(24), helpstring("属性serverIP")] BSTR serverIP;
			[id(25), helpstring("属性serverPort")] BSTR serverPort;
		methods:
	};

	//  CVideoPluginCtrl 的类信息
	[
		uuid(95452421-C307-4060-9581-84C3F6274D55)
	]
	coclass VideoPlugin
	{
		[default] dispinterface _DVideoPlugin;
		[default, source] dispinterface _DVideoPluginEvents;
	};

};
